version: '3.8'

services:
  db-customer:
    container_name: db-customer
    image: postgres:latest
    restart: always
    networks: 
      - softka-network
    ports:
      - "15430:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty

  db-account:
    container_name: db-account
    image: postgres:latest
    restart: always
    networks: 
      - softka-network
    ports:
      - "15431:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - softka-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - softka-network

  
  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    container_name: customer-service
    depends_on: 
      - kafka
      - zookeeper
      - db-customer
    environment:
      - DB_HOST=db-customer
      - DB_NAME=postgres
      - DB_PASSWORD=qwerty
      - DB_PORT=5432
      - DB_USER=postgres
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - client-topic=CLIENTS
    ports:
      - "8001:8001"
    networks:
      - softka-network


  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: account-service
    depends_on: 
      - customer-service
      - kafka
      - zookeeper
      - db-account
    environment:
      - DB_HOST=db-account
      - DB_NAME=postgres
      - DB_PASSWORD=qwerty
      - DB_PORT=5432
      - DB_USER=postgres
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - client-topic=CLIENTS
      - EXTERNAL_SERVICE_URL=http://customer-service:8001
    ports:
      - "8000:8000"
    networks:
      - softka-network
  
networks:
  softka-network:
    driver: bridge
  